#ifdef TNY_ENUMS_H

/* These are fakes for gtk-doc */

G_BEGIN_DECLS

typedef enum  {
	TNY_ACCOUNT_TYPE_STORE,
	TNY_ACCOUNT_TYPE_TRANSPORT
} TnyAccountType;

typedef enum {
	TNY_ACCOUNT_STORE_ACCOUNT_CHANGED,
	TNY_ACCOUNT_STORE_ACCOUNT_INSERTED,
	TNY_ACCOUNT_STORE_ACCOUNT_REMOVED,
	TNY_ACCOUNT_STORE_ACCOUNTS_RELOADED,
	TNY_ACCOUNT_STORE_LAST_SIGNAL
} TnyAccountStoreSignal;

typedef enum  {
	TNY_ALERT_TYPE_INFO,
	TNY_ALERT_TYPE_WARNING,
	TNY_ALERT_TYPE_ERROR
} TnyAlertType;

typedef enum {
	TNY_ACCOUNT_STORE_TRANSPORT_ACCOUNTS,
	TNY_ACCOUNT_STORE_STORE_ACCOUNTS,
	TNY_ACCOUNT_STORE_BOTH
} TnyGetAccountsRequestType;

typedef enum {
	TNY_DEVICE_CONNECTION_CHANGED,
	TNY_DEVICE_LAST_SIGNAL
} TnyDeviceSignal;

typedef enum {
	TNY_FOLDER_FOLDER_INSERTED,
	TNY_FOLDER_FOLDERS_RELOADED,
	TNY_FOLDER_LAST_SIGNAL
} TnyFolderSignal;

typedef enum {
   TNY_FOLDER_STORE_QUERY_OPTION_SUBSCRIBED = 1<<1,
   TNY_FOLDER_STORE_QUERY_OPTION_UNSUBSCRIBED = 1<<2,
   TNY_FOLDER_STORE_QUERY_OPTION_MATCH_ON_NAME = 1<<3,
   TNY_FOLDER_STORE_QUERY_OPTION_MATCH_ON_ID = 1<<4
} TnyFolderStoreQueryOption;

typedef enum {
	TNY_HEADER_FLAG_ANSWERED = 1<<0,
	TNY_HEADER_FLAG_DELETED = 1<<1,
	TNY_HEADER_FLAG_DRAFT = 1<<2,
	TNY_HEADER_FLAG_FLAGGED = 1<<3,
	TNY_HEADER_FLAG_SEEN = 1<<4,
	TNY_HEADER_FLAG_ATTACHMENTS = 1<<5,
	TNY_HEADER_FLAG_ANSWERED_ALL = 1<<6,
	TNY_HEADER_FLAG_JUNK = 1<<7,
	TNY_HEADER_FLAG_SECURE = 1<<8,
	TNY_HEADER_FLAG_FOLDER_FLAGGED = 1<<16,
	TNY_HEADER_FLAG_JUNK_LEARN = 1<<30,
	TNY_HEADER_FLAG_USER = 1<<31
} TnyHeaderFlags;


G_END_DECLS

#endif
